image: gcc

before_script:
#  - apt-get update -qq && apt-get install -y -qq liballegro5-dev valgrind
      
stages:
    - build
    
build_lib:
  stage: build 
  script:
    - make
    
# build_examples:  
  stage: build
  script:
    - cd examples ; make ; ./valgrind.sh
